# Site settings
title: Felip Barbosa de Medeiros
description: 'Pai, empres√°rio e programador.'
url: 'https://felip.com.br/'
baseurl: ''
link: 'https://felip.com.br'
locale: pt_BR

author:
  name: 'Felip Barbosa de Medeiros'
  email: www@felip.com.br
  twitter_username: fxlip
  github_username:  fel1p
  telegram_username: fel1p
  steam_username: mked0n
  psn_username: mked0n
  strava_link: 39646001
  discord_link: q5gWd6P

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 3
excerpt_separator: <!--mais-->
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-localization']
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
