title: "Felip Barbosa de Medeiros"
email: fxlip@tuta.io
description: "Diário de estudos focado em Linux e Tecnologia. Documentações técnicas, notícias e materiais relevantes sobre o software livre e asociedade."
url: "https://fxlip.com"

header_pages:
  - sobre.md
  - index.html
  - linux.md
  - arquivos.md
  - setup.md

footer: 'me manda um <a href="mailto:fxlip@tuta.io">e-mail</a> ツ'

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Pagination (infinite scroll)
paginate: 5
paginate_path: "/page/:num/"

sass:
  style: compressed
  quiet_deps: true

# Timezone
timezone: America/Sao_Paulo

# TIME TRAVEL FIX:
future: true

# Collections
collections:
  root:
    output: true
    permalink: /:path/

exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - LICENSE