title: "Felip Barbosa de Medeiros"
email: fxlip@tuta.io
description: "Diário de estudos focado em Linux e Tecnologia. Documentação técnica, artigos e notas sobre software livre e sociedade."
url: "https://felip.com.br"

header_pages:
  - index.html
  - about.md
  - linux.md
  - files.md
  - setup.md

footer: 'me manda um <a href="mailto:fxlip@tuta.io">e-mail</a> ツ'

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Pagination (infinite scroll)
paginate: 5
paginate_path: "/page/:num/"

sass:
  style: compressed
  quiet_deps: true

# Timezone
timezone: America/Sao_Paulo

# TIME TRAVEL FIX:
future: true

# Collections
collections:
  root:
    output: true
    permalink: /:path/

exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - LICENSE