# Site settings
title: Felip Barbosa de Medeiros
description_site: 'Membro da <a href="https://fsf.org" target="_blank" rel="noopener noreferrer">FSF</a> desde 2018, sou um analista de sistemas com experiência em software livre, programação, mineração de dados, infraestrutura e segurança.<br>
Atualmente no <a href="https://bsbcapital.com.br" target="_blank" rel="noopener noreferrer" >Jornal Brasília Capital</a>, antes na <a href="https://veganalimentos.com.br" target="_blank" rel="noopener noreferrer">Vegan</a>, <a href="https://www.hortminasdf.com.br/" target="_blank" rel="noopener noreferrer">HortMinas</a> e <a href="http://www.cebgas.com.br/" target="_blank" rel="noopener noreferrer">CEBGAS</a>.'
description_seo: 'Membro da FSF desde 2018, sou analista de sistemas com experiência em software livre, programação, mineração de dados, infraestrutura e segurança.'
url: 'https://felip.com.br/'
baseurl: ''
link: 'https://felip.com.br'
locale: pt_BR

author:
  name: 'Felip Barbosa de Medeiros'
  email: felip42@gmail.com
  twitter_username: fxlip
  instagram_username: bvrbosv
  keybase_username: fxlip
  github_username: fxlip
  telegram_username: fxlip
  steam_username: mked0n
  psn_username: mked0n
  strava_link: 39646001
  discord_link: q5gWd6P
  whatsapp_number: 5561996220406

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 3
excerpt_separator: <!--mais-->
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-localization', 'jekyll-redirect-from', 'jekyll-seo-tag']
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
