name = "fxlip-visitor-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[deployment]
preview_urls = false # Desativa as URLs de preview autom√°ticas

[vars]
ALLOWED_ORIGIN = "https://fxlip.com"

# SALT must be set via: wrangler secret put SALT

[[kv_namespaces]]
binding = "VISITORS"
id = "27924646fab64f9a82704b69d40d1568"
